"""
analyse_E4.py — E4 tables: does the format/template dependence survive transfer?

Per target:
  E4a  150 AdvBench IDs (the same ones E1 used) x {bare, steps} x {base, shuffled, authors}
  E4b  150 SafeBench-315 positions x {TPG on, off} x {base, authors}

Four of each target's ten cells come from byte-identical existing transfer runs,
subset to the frozen ID lists (verified identical by build_E4_configs.py). The
rest are generated by jobs/E4_transfer.sh.

The Qwen2-VL-7B column is computed on the SAME rows from the pilot's own outputs,
free of new generation: E1 already used these exact 150 AdvBench IDs, and E2's
315-row outputs are subset to the E4b positions.

Runs on partial results. Metrics, counts and IDs only - no completion text.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, REPO)
sys.path.insert(0, HERE)

import metrics as M  # noqa: E402
import stats as S    # noqa: E402

GEN = os.path.join(REPO, "aaai_ugc", "results", "E4", "gen")
OUT = os.path.join(REPO, "aaai_ugc", "results", "E4")
CFG = os.path.join(REPO, "aaai_ugc", "configs")
os.makedirs(OUT, exist_ok=True)

QWEN2VL = "Qwen/Qwen2-VL-7B-Instruct"
TARGETS = {"qvlchat": "Qwen/Qwen-VL-Chat", "llava": "llava-hf/llava-v1.6-mistral-7b-hf"}
SHORT = {"qvlchat": "Qwen-VL-Chat", "llava": "LLaVA-1.6", "qwen2vl": "Qwen2-VL-7B (pilot)"}

# Cells sourced from existing runs instead of regenerated.
REUSE = {
    ("E4a", "bare", "authors"): "cmp_img_abraw",
    ("E4a", "steps", "authors"): "cmp_img_abnorm",
    ("E4b", "on", "authors"): "cmp_img_sb315",
    ("E4b", "off", "base"): "noattack_safebench_matrix",
}
CONDS = ["base", "shuffled", "authors"]
FORMATS = ["bare", "steps"]


def ids(name: str) -> list:
    return [int(x) for x in open(os.path.join(CFG, name)).read().split()]


ADV_IDS = ids("E1_ids.txt")
SB_IDS = ids("E4b_ids.txt")


def git_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                       cwd=REPO, text=True).strip()
    except Exception:
        return "unknown"


def _read(path: str) -> pd.DataFrame | None:
    if not os.path.exists(path):
        return None
    d = pd.read_csv(path)
    return d if "attack_success" in d.columns else None


def load_cell(exp: str, a: str, b: str, model: str, judge: str = "v3") -> pd.DataFrame | None:
    """Load one cell, from a new E4 run or from the reused existing run (subset)."""
    suf = "_harmbench_v3.csv" if judge == "v3" else "_harmbench.csv"
    key = (exp, a, b)
    if key in REUSE:
        d = _read(os.path.join(REPO, "results", REUSE[key], model + suf))
        if d is None:
            return None
        sel = ADV_IDS if exp == "E4a" else SB_IDS
        if len(d) <= max(sel):
            return None
        return d.iloc[sel].reset_index(drop=True)
    cfg = f"E4a_{a}_{b}" if exp == "E4a" else f"E4b_tpg{a}_{b}"
    return _read(os.path.join(GEN, cfg, model + suf))


def load_pilot(exp: str, a: str, b: str, judge: str = "v3") -> pd.DataFrame | None:
    """The pilot's Qwen2-VL numbers on exactly these rows, from E1/E2 outputs."""
    suf = "_harmbench_v3.csv" if judge == "v3" else "_harmbench.csv"
    base = os.path.join(REPO, "aaai_ugc", "results", "gen")
    if exp == "E4a":
        d = _read(os.path.join(base, f"E1_{a}_{b}", QWEN2VL + suf))
        return d  # E1 already ran exactly these 150 ids, in this order
    d = _read(os.path.join(base, f"E2_tpg{a}_{b}", QWEN2VL + suf))
    if d is None or len(d) <= max(SB_IDS):
        return None
    return d.iloc[SB_IDS].reset_index(drop=True)


def succ(d: pd.DataFrame) -> np.ndarray:
    return d["attack_success"].astype(bool).values


def cell_stats(d: pd.DataFrame | None) -> dict | None:
    if d is None:
        return None
    s = succ(d)
    ci = S.wilson_ci(int(s.sum()), len(s))
    m = M.summarise(d)
    return {"n": len(s), "k": int(s.sum()), "asr": 100 * ci.p, "lo": 100 * ci.lo,
            "hi": 100 * ci.hi, "nrr": 100 * m["nrr"], "prefix": 100 * m["prefix_rate"],
            "list": 100 * m["list_rate"], "ptr": 100 * m["prefix_then_refuse_rate"],
            "medlen": m["median_answer_len"]}


def fmt(c: dict | None, w: int = 22) -> str:
    return f"{'—':>{w}s}" if c is None else f"{c['asr']:>9.2f} [{c['lo']:4.1f},{c['hi']:5.1f}]"


def banner(t: str) -> None:
    print("\n" + "=" * 78); print(t); print("=" * 78)


def do_target(tag: str, model: str, rows: list, out: dict) -> None:
    banner(f"E4 — {SHORT[tag]}  ({model})")
    mats = {}

    # ── E4a: phrasing contrast ───────────────────────────────────────────────
    got_any = False
    for judge in ("v3", "v1"):
        lines = []
        for f_ in FORMATS:
            cells = {}
            for c in CONDS:
                d = load_cell("E4a", f_, c, model, judge)
                st = cell_stats(d)
                if st:
                    got_any = True
                    if judge == "v3":
                        mats[("E4a", f_, c)] = succ(d)
                    rows.append({"target": tag, "exp": "E4a", "judge": judge,
                                 "format": f_, "condition": c, "reused":
                                 ("E4a", f_, c) in REUSE, **st})
                cells[c] = st
            lines.append((f_, cells))
        if any(any(v for v in c.values()) for _, c in lines):
            print(f"\n-- E4a ASR % [Wilson 95% CI], judge {judge} (n=150 AdvBench ids) --")
            print(f"  {'format':9s}" + "".join(f"{c:>22s}" for c in CONDS))
            for f_, cells in lines:
                print(f"  {f_:9s}" + "".join(fmt(cells[c]) for c in CONDS))

    if got_any:
        print(f"\n-- E4a uplift over `base`, paired, exact McNemar (judge v3) --")
        up = {}
        for f_ in FORMATS:
            if ("E4a", f_, "base") not in mats:
                continue
            b = mats[("E4a", f_, "base")]
            for c in ("shuffled", "authors"):
                if ("E4a", f_, c) not in mats:
                    continue
                a = mats[("E4a", f_, c)]
                mc = S.mcnemar_exact(a, b)
                u = 100 * (a.mean() - b.mean())
                up[(f_, c)] = u
                sig = "ns" if mc.p_value >= 0.05 else "*"
                print(f"  {f_:6s} {c:9s} uplift={u:+7.2f}  b={mc.b:3d} c={mc.c:3d} "
                      f"p={mc.p_value:.3g} {sig}")
                rows.append({"target": tag, "exp": "E4a_uplift", "judge": "v3",
                             "format": f_, "condition": c, "uplift_pts": u,
                             "mcnemar_b": mc.b, "mcnemar_c": mc.c, "mcnemar_p": mc.p_value})
        if ("bare", "authors") in up and ("steps", "authors") in up:
            k = up[("steps", "authors")] - up[("bare", "authors")]
            out.setdefault(tag, {})["key_contrast_pts"] = k
            out[tag]["uplift_bare"] = up[("bare", "authors")]
            out[tag]["uplift_steps"] = up[("steps", "authors")]
            print(f"\n  KEY CONTRAST uplift(steps)-uplift(bare) = {k:+.2f} pts")
            print(f"    vs Qwen2-VL-7B on the SAME 150 ids: +57.33 pts")

    # ── E4b: template ablation ───────────────────────────────────────────────
    for judge in ("v3", "v1"):
        shown = False
        for tpg in ("on", "off"):
            cells = {}
            for c in ("base", "authors"):
                d = load_cell("E4b", tpg, c, model, judge)
                st = cell_stats(d)
                if st:
                    if judge == "v3":
                        mats[("E4b", tpg, c)] = succ(d)
                    rows.append({"target": tag, "exp": "E4b", "judge": judge,
                                 "tpg": tpg, "condition": c,
                                 "reused": ("E4b", tpg, c) in REUSE, **st})
                cells[c] = st
            if any(cells.values()):
                if not shown:
                    print(f"\n-- E4b ASR % [Wilson 95% CI], judge {judge} "
                          f"(n=150 SafeBench rows) --")
                    print(f"  {'TPG':5s}{'base':>22s}{'authors':>22s}{'uplift':>9s}")
                    shown = True
                u = (f"{cells['authors']['asr']-cells['base']['asr']:>+9.2f}"
                     if cells["base"] and cells["authors"] else f"{'—':>9s}")
                print(f"  {tpg:5s}{fmt(cells['base'])}{fmt(cells['authors'])}{u}")

    ups = {}
    for tpg in ("on", "off"):
        if ("E4b", tpg, "base") in mats and ("E4b", tpg, "authors") in mats:
            a, b = mats[("E4b", tpg, "authors")], mats[("E4b", tpg, "base")]
            mc = S.mcnemar_exact(a, b)
            ups[tpg] = 100 * (a.mean() - b.mean())
            sig = "ns" if mc.p_value >= 0.05 else "*"
            print(f"  TPG {tpg:3s}: uplift={ups[tpg]:+7.2f}  b={mc.b:3d} c={mc.c:3d} "
                  f"p={mc.p_value:.3g} {sig}")
            rows.append({"target": tag, "exp": "E4b_uplift", "judge": "v3", "tpg": tpg,
                         "uplift_pts": ups[tpg], "mcnemar_b": mc.b, "mcnemar_c": mc.c,
                         "mcnemar_p": mc.p_value})
    if len(ups) == 2:
        inter = ups["on"] - ups["off"]
        out.setdefault(tag, {})["template_interaction_pts"] = inter
        out[tag]["uplift_tpg_on"] = ups["on"]
        out[tag]["uplift_tpg_off"] = ups["off"]
        print(f"\n  INTERACTION uplift(on)-uplift(off) = {inter:+.2f} pts")

    # ── response shape ───────────────────────────────────────────────────────
    sh = [r for r in rows if r["target"] == tag and r["judge"] == "v3"
          and r["exp"] in ("E4a", "E4b")]
    if sh:
        print(f"\n-- response shape, judge v3 (prefix is trivially 0 when TPG off) --")
        print(f"  {'cell':24s} {'NRR':>6s} {'pfx%':>6s} {'list%':>6s} {'PTR%':>6s} {'medlen':>7s}")
        for r in sh:
            name = (f"E4a {r.get('format')}/{r['condition']}" if r["exp"] == "E4a"
                    else f"E4b tpg{r.get('tpg')}/{r['condition']}")
            print(f"  {name:24s} {r['nrr']:>6.1f} {r['prefix']:>6.1f} {r['list']:>6.1f} "
                  f"{r['ptr']:>6.1f} {r['medlen']:>7.0f}")


def pilot_on_same_rows(rows: list, out: dict) -> None:
    """Qwen2-VL on the identical rows — the free comparison column."""
    banner("Qwen2-VL-7B (pilot) recomputed on the IDENTICAL E4 rows — no new generation")
    mats = {}
    for f_ in FORMATS:
        for c in CONDS:
            d = load_pilot("E4a", f_, c)
            st = cell_stats(d)
            if st:
                mats[("E4a", f_, c)] = succ(d)
                rows.append({"target": "qwen2vl", "exp": "E4a", "judge": "v3",
                             "format": f_, "condition": c, "reused": True, **st})
    for tpg in ("on", "off"):
        for c in ("base", "authors"):
            d = load_pilot("E4b", tpg, c)
            st = cell_stats(d)
            if st:
                mats[("E4b", tpg, c)] = succ(d)
                rows.append({"target": "qwen2vl", "exp": "E4b", "judge": "v3",
                             "tpg": tpg, "condition": c, "reused": True, **st})
    up = {}
    for f_ in FORMATS:
        if ("E4a", f_, "base") in mats and ("E4a", f_, "authors") in mats:
            a, b = mats[("E4a", f_, "authors")], mats[("E4a", f_, "base")]
            up[f_] = 100 * (a.mean() - b.mean())
    if len(up) == 2:
        out.setdefault("qwen2vl", {})["uplift_bare"] = up["bare"]
        out["qwen2vl"]["uplift_steps"] = up["steps"]
        out["qwen2vl"]["key_contrast_pts"] = up["steps"] - up["bare"]
        print(f"  E4a uplift(bare)={up['bare']:+.2f}  uplift(steps)={up['steps']:+.2f}  "
              f"KEY CONTRAST={up['steps']-up['bare']:+.2f} pts")
    ups = {}
    for tpg in ("on", "off"):
        if ("E4b", tpg, "base") in mats and ("E4b", tpg, "authors") in mats:
            a, b = mats[("E4b", tpg, "authors")], mats[("E4b", tpg, "base")]
            ups[tpg] = 100 * (a.mean() - b.mean())
    if len(ups) == 2:
        out["qwen2vl"]["uplift_tpg_on"] = ups["on"]
        out["qwen2vl"]["uplift_tpg_off"] = ups["off"]
        out["qwen2vl"]["template_interaction_pts"] = ups["on"] - ups["off"]
        print(f"  E4b uplift(on)={ups['on']:+.2f}  uplift(off)={ups['off']:+.2f}  "
              f"INTERACTION={ups['on']-ups['off']:+.2f} pts  (on the 150-row subset)")


def main() -> None:
    rows, out = [], {}
    pilot_on_same_rows(rows, out)
    for tag, model in TARGETS.items():
        do_target(tag, model, rows, out)

    df = pd.DataFrame(rows)
    if not df.empty:
        df.to_csv(os.path.join(OUT, "E4_all_cells.csv"), index=False)

    if out:
        banner("E4 SUMMARY — does the dependence survive transfer?")
        print(f"  {'target':22s} {'uplift(bare)':>13s} {'uplift(steps)':>14s} "
              f"{'KEY CONTRAST':>13s} {'TPG on':>8s} {'TPG off':>8s} {'INTERACT':>9s}")
        for t in ("qwen2vl", "qvlchat", "llava"):
            if t not in out:
                continue
            o = out[t]
            g = lambda k: f"{o[k]:+.2f}" if k in o else "—"
            print(f"  {SHORT[t]:22s} {g('uplift_bare'):>13s} {g('uplift_steps'):>14s} "
                  f"{g('key_contrast_pts'):>13s} {g('uplift_tpg_on'):>8s} "
                  f"{g('uplift_tpg_off'):>8s} {g('template_interaction_pts'):>9s}")

    with open(os.path.join(OUT, "E4_summary.json"), "w") as f:
        json.dump({"git_commit": git_commit(),
                   "run_utc": datetime.now(timezone.utc).isoformat(),
                   "adv_ids_file": "E1_ids.txt", "sb_ids_file": "E4b_ids.txt",
                   "n_per_cell": 150, "targets": out}, f, indent=2, default=str)
    banner("E4 written to aaai_ugc/results/E4/")


if __name__ == "__main__":
    main()
